- index.bs
- index.html
This commit creates the basic template for a Bikeshed spec to use for the Controlled Frame API and includes the generated HTML.
> Create starter Bikeshed spec files

- test_app/README.md
- test_app/common.js
- test_app/controlledframe_api.js
- test_app/icon.svg
- test_app/index.html
- test_app/index.js
- test_app/iwa_http_server.py
- test_app/manifest.webmanifest
- test_app/style.css
- test_app/sw.js
This change adds the Controlled Frame test app to the test_app/ directory. The README contained within the directory explains the steps necessary to launch the app as an Isolated Web App with the <controlledframe> tag enabled.
> Add Controlled Frame test app

- EXPLAINER.md
Since the old EXPLAINER.md was removed, add a redirect from that file to README.md.
> Add EXPLAINER.md redirect

- index.bs
This commit adds an Abstract section to provide an overview of the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/controlled-frame/pull/14.html" title="Last updated on May 8, 2023, 4:18 PM UTC (b00bf93)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/chasephillips/controlled-frame/14/2923483...odejesush:b00bf93.html" title="Last updated on May 8, 2023, 4:18 PM UTC (b00bf93)">Diff</a>
> spec: Add Abstract section

- index.bs
This commit populates the Introduction section of the spec using the Introduction of the explainer as reference.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/controlled-frame/pull/15.html" title="Last updated on May 9, 2023, 3:51 PM UTC (ec9cd33)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/chasephillips/controlled-frame/15/3f86fc3...odejesush:ec9cd33.html" title="Last updated on May 9, 2023, 3:51 PM UTC (ec9cd33)">Diff</a>
> spec: Populate Introduction

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/chasephillips/controlled-frame/pull/23.html" title="Last updated on Jun 14, 2023, 11:42 PM UTC (2e06c3a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/chasephillips/controlled-frame/23/c04bc52...2e06c3a.html" title="Last updated on Jun 14, 2023, 11:42 PM UTC (2e06c3a)">Diff</a>
> spec: Begin splitting up the IDL section into a new "API" area

- index.bs
Also include basic spec API structure section headings.
***
<a href="https://pr-preview.s3.amazonaws.com/chasephillips/controlled-frame/pull/25.html" title="Last updated on Jun 20, 2023, 11:21 PM UTC (d1b2fd4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/chasephillips/controlled-frame/25/73d6aa9...d1b2fd4.html" title="Last updated on Jun 20, 2023, 11:21 PM UTC (d1b2fd4)">Diff</a>
> spec: Add methods associated with Controlled Frame element

- index.bs
This commit adds a Security, Privacy, and Accessbility section using the corresponding sections from the explainer.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/controlled-frame/pull/18.html" title="Last updated on Aug 4, 2023, 9:42 PM UTC (ed113ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/chasephillips/controlled-frame/18/db92408...odejesush:ed113ba.html" title="Last updated on Aug 4, 2023, 9:42 PM UTC (ed113ba)">Diff</a>
> spec: Security, Privacy, & Accessiblity considerations

- w3c.json
Needed by tools that crawl WICG repositories
Cc @yoavweiss, I put your name in there as contact. Feel free to update if needed!
> Adding baseline w3c.json

- README.md
Update links to wicg.github.com
> Update README.md to use wicg.github.com

- test_app/index.html
- test_app/src/controlledframe_api.js
This removes all webview APIs that were removed from Controlled Frame, and updates all remaining Controlled Frame APIs to use the Promise form instead of callback.
> test_app: Switch to Promise-based API calls

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/pull/51.html" title="Last updated on Nov 20, 2024, 9:21 PM UTC (32f4f53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/51/71f3f2f...32f4f53.html" title="Last updated on Nov 20, 2024, 9:21 PM UTC (32f4f53)">Diff</a>
> spec: Note the spec as part of the WICG group

- .github/workflows/build-test-app.yml
This updates the "Setup Node" step to run in the test_app directory.
> test_app: Fix test_app autodeploy workflow

- .github/workflows/build-test-app.yml
- test_app/bump_version.js
- test_app/public/.well-known/manifest.webmanifest
This fixes several bugs in the auto-release workflow/scripts. Tested in my fork of the repo.
> Fix auto-release setup

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/pull/57.html" title="Last updated on Jan 8, 2025, 6:13 AM UTC (148585c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/57/e091229...148585c.html" title="Last updated on Jan 8, 2025, 6:13 AM UTC (148585c)">Diff</a>
> spec: Update editors and create Acknowledgements

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/66.html" title="Last updated on Feb 14, 2025, 12:25 AM UTC (cedf5a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/66/38c0477...robbiemc:cedf5a6.html" title="Last updated on Feb 14, 2025, 12:25 AM UTC (cedf5a6)">Diff</a>
> spec: Fix WebRequest property name

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/pull/64.html" title="Last updated on Feb 14, 2025, 12:29 AM UTC (04b335c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/64/6ccb85f...04b335c.html" title="Last updated on Feb 14, 2025, 12:29 AM UTC (04b335c)">Diff</a>
> Spec: Document Controlled Frame attributes and methods

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/pull/68.html" title="Last updated on Feb 18, 2025, 8:39 AM UTC (be75e9d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/68/381014c...be75e9d.html" title="Last updated on Feb 18, 2025, 8:39 AM UTC (be75e9d)">Diff</a>
> spec: Add text related to the partition attribute

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/pull/69.html" title="Last updated on Feb 18, 2025, 9:13 PM UTC (e24ae7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/69/06a40b2...e24ae7f.html" title="Last updated on Feb 18, 2025, 9:13 PM UTC (e24ae7f)">Diff</a>
> Spec: Add spec enhancements around base IDL and scripting methods

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/70.html" title="Last updated on Feb 25, 2025, 11:07 PM UTC (a9b2811)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/70/270197f...ZelinLiu2022:a9b2811.html" title="Last updated on Feb 25, 2025, 11:07 PM UTC (a9b2811)">Diff</a>
> ContextMenus API Spec

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/71.html" title="Last updated on Feb 25, 2025, 11:44 PM UTC (942cb75)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/71/dd4cb2a...robbiemc:942cb75.html" title="Last updated on Feb 25, 2025, 11:44 PM UTC (942cb75)">Diff</a>
> spec: Finish WebRequest specification

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/pull/74.html" title="Last updated on Feb 27, 2025, 11:02 PM UTC (53547ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/74/06a40b2...53547ea.html" title="Last updated on Feb 27, 2025, 11:02 PM UTC (53547ea)">Diff</a>
> spec: Add Zelin as an editor, update Chase's email address

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/84.html" title="Last updated on Mar 7, 2025, 9:06 PM UTC (e4e61c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/84/df0da6e...ZelinLiu2022:e4e61c8.html" title="Last updated on Mar 7, 2025, 9:06 PM UTC (e4e61c8)">Diff</a>
> spec: Improve IDL reference coverage for Context Menus

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/85.html" title="Last updated on Mar 14, 2025, 12:22 AM UTC (b9d0ece)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/85/2893a0d...ZelinLiu2022:b9d0ece.html" title="Last updated on Mar 14, 2025, 12:22 AM UTC (b9d0ece)">Diff</a>
> spec: update Context Menus async methods

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/88.html" title="Last updated on Mar 19, 2025, 9:42 PM UTC (d47abb2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/88/2319122...ZelinLiu2022:d47abb2.html" title="Last updated on Mar 19, 2025, 9:42 PM UTC (d47abb2)">Diff</a>
> spec: Events part 1 = IDLs and some dispatch algorithms 

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/91.html" title="Last updated on Mar 28, 2025, 1:33 AM UTC (b24d48e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/91/3ff6211...ZelinLiu2022:b24d48e.html" title="Last updated on Mar 28, 2025, 1:33 AM UTC (b24d48e)">Diff</a>
> spec: Add more methods and monkey-patching for events

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/92.html" title="Last updated on Mar 27, 2025, 9:20 PM UTC (8ac2fef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/92/3ff6211...robbiemc:8ac2fef.html" title="Last updated on Mar 27, 2025, 9:20 PM UTC (8ac2fef)">Diff</a>
> spec: Expand clearData spec

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/96.html" title="Last updated on Mar 28, 2025, 10:02 PM UTC (6a9b130)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/96/e793557...ZelinLiu2022:6a9b130.html" title="Last updated on Mar 28, 2025, 10:02 PM UTC (6a9b130)">Diff</a>
> Spec: Add zoom

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/95.html" title="Last updated on Mar 29, 2025, 12:01 AM UTC (41587a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/95/2b73fdb...robbiemc:41587a8.html" title="Last updated on Mar 29, 2025, 12:01 AM UTC (41587a8)">Diff</a>
> spec: Patch in script injection

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/94.html" title="Last updated on Apr 22, 2025, 9:03 PM UTC (c8e1558)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/94/3816617...robbiemc:c8e1558.html" title="Last updated on Apr 22, 2025, 9:03 PM UTC (c8e1558)">Diff</a>
> spec: Redo the history navigation algorithm

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/99.html" title="Last updated on Apr 24, 2025, 5:11 PM UTC (4fae529)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/99/ab601fe...robbiemc:4fae529.html" title="Last updated on Apr 24, 2025, 5:11 PM UTC (4fae529)">Diff</a>
> spec: Change boolean formatting and promise creation

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/101.html" title="Last updated on Apr 29, 2025, 11:14 PM UTC (26d89f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/101/f49a08f...robbiemc:26d89f8.html" title="Last updated on Apr 29, 2025, 11:14 PM UTC (26d89f8)">Diff</a>
> spec: Fix threading issues in spec

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/102.html" title="Last updated on May 1, 2025, 12:41 AM UTC (7ca97ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/102/d596257...robbiemc:7ca97ef.html" title="Last updated on May 1, 2025, 12:41 AM UTC (7ca97ef)">Diff</a>
> spec: Address feedback in WebRequestEventDetails creation algorithm

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/106.html" title="Last updated on May 2, 2025, 5:29 PM UTC (3a48e60)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/106/2b1085f...ZelinLiu2022:3a48e60.html" title="Last updated on May 2, 2025, 5:29 PM UTC (3a48e60)">Diff</a>
> spec: Update ContextMenuProperties

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/104.html" title="Last updated on May 2, 2025, 6:04 PM UTC (ec5848e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/104/2b1085f...robbiemc:ec5848e.html" title="Last updated on May 2, 2025, 6:04 PM UTC (ec5848e)">Diff</a>
> spec: Update audio related API spec

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/107.html" title="Last updated on May 7, 2025, 9:41 PM UTC (58669ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/107/df0bccd...ZelinLiu2022:58669ae.html" title="Last updated on May 7, 2025, 9:41 PM UTC (58669ae)">Diff</a>
> spec: address constructor feedback

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/112.html" title="Last updated on May 8, 2025, 5:13 PM UTC (d6863e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/112/ae483d9...ZelinLiu2022:d6863e0.html" title="Last updated on May 8, 2025, 5:13 PM UTC (d6863e0)">Diff</a>
> spec: Update excludeMatches

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/111.html" title="Last updated on May 8, 2025, 5:55 PM UTC (ed5aa2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/111/ae483d9...ZelinLiu2022:ed5aa2f.html" title="Last updated on May 8, 2025, 5:55 PM UTC (ed5aa2f)">Diff</a>
> spec: Remove use of 'will' in attributes

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/108.html" title="Last updated on May 8, 2025, 6:15 PM UTC (1cde2c2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/108/e72c273...robbiemc:1cde2c2.html" title="Last updated on May 8, 2025, 6:15 PM UTC (1cde2c2)">Diff</a>
> spec: Spec element removal and describe canGoForward

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/113.html" title="Last updated on May 8, 2025, 6:40 PM UTC (e79a029)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/113/cf12441...robbiemc:e79a029.html" title="Last updated on May 8, 2025, 6:40 PM UTC (e79a029)">Diff</a>
> spec: Add more ContentScriptDetails validation

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/114.html" title="Last updated on May 8, 2025, 6:59 PM UTC (4438d79)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/114/cf12441...robbiemc:4438d79.html" title="Last updated on May 8, 2025, 6:59 PM UTC (4438d79)">Diff</a>
> spec: Add explicit sucess flag to script fetch callback

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/120.html" title="Last updated on May 13, 2025, 2:52 AM UTC (24beb23)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/120/6f19a98...ZelinLiu2022:24beb23.html" title="Last updated on May 13, 2025, 2:52 AM UTC (24beb23)">Diff</a>
> spec: Link RGO to navigable's node document

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/118.html" title="Last updated on May 13, 2025, 2:03 AM UTC (406ba72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/118/6f19a98...ZelinLiu2022:406ba72.html" title="Last updated on May 13, 2025, 2:03 AM UTC (406ba72)">Diff</a>
> spec: Use USVString on injection files

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/117.html" title="Last updated on May 13, 2025, 4:54 AM UTC (44d11d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/117/c71376f...robbiemc:44d11d6.html" title="Last updated on May 13, 2025, 4:54 AM UTC (44d11d6)">Diff</a>
> spec: Add getters for IDL-exposed interface properties

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/121.html" title="Last updated on May 13, 2025, 7:56 PM UTC (c0e2758)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/121/331a35c...ZelinLiu2022:c0e2758.html" title="Last updated on May 13, 2025, 7:56 PM UTC (c0e2758)">Diff</a>
> spec: Use variable for [=this=] in parallel

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/127.html" title="Last updated on May 14, 2025, 6:48 PM UTC (a15fb6b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/127/d61b659...ZelinLiu2022:a15fb6b.html" title="Last updated on May 14, 2025, 6:48 PM UTC (a15fb6b)">Diff</a>
> spec: 'inject content script into a document' minor readibility refactor

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/126.html" title="Last updated on May 14, 2025, 6:41 PM UTC (e54b5ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/126/d61b659...ZelinLiu2022:e54b5ed.html" title="Last updated on May 14, 2025, 6:41 PM UTC (e54b5ed)">Diff</a>
> spec: Move resolve/reject embedder promise to common infrastructure

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/125.html" title="Last updated on May 14, 2025, 8:32 PM UTC (3443541)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/125/d61b659...ZelinLiu2022:3443541.html" title="Last updated on May 14, 2025, 8:32 PM UTC (3443541)">Diff</a>
> spec: |scriptNameList| to 'null' instead of 'undefined'

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/124.html" title="Last updated on May 14, 2025, 8:35 PM UTC (1f52a32)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/124/d61b659...ZelinLiu2022:1f52a32.html" title="Last updated on May 14, 2025, 8:35 PM UTC (1f52a32)">Diff</a>
> spec: clearData minor fix

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/128.html" title="Last updated on May 14, 2025, 8:40 PM UTC (f2cf52a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/128/d61b659...robbiemc:f2cf52a.html" title="Last updated on May 14, 2025, 8:40 PM UTC (f2cf52a)">Diff</a>
> spec: Use existing about:blank matching algorithm

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/129.html" title="Last updated on May 14, 2025, 9:36 PM UTC (8bd2b57)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/129/12144e3...robbiemc:8bd2b57.html" title="Last updated on May 14, 2025, 9:36 PM UTC (8bd2b57)">Diff</a>
> spec: Move some behavior description into notes

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/131.html" title="Last updated on May 15, 2025, 1:04 AM UTC (efb8ce3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/131/91428c3...robbiemc:efb8ce3.html" title="Last updated on May 15, 2025, 1:04 AM UTC (efb8ce3)">Diff</a>
> spec: Add notes about why injectScript works the way it does

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/130.html" title="Last updated on May 15, 2025, 1:23 AM UTC (82334b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/130/91428c3...robbiemc:82334b9.html" title="Last updated on May 15, 2025, 1:23 AM UTC (82334b9)">Diff</a>
> spec: Refactor how match patterns are spec'd

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/132.html" title="Last updated on May 15, 2025, 8:00 PM UTC (808177f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/132/48e2e71...robbiemc:808177f.html" title="Last updated on May 15, 2025, 8:00 PM UTC (808177f)">Diff</a>
> spec: Improve how IDL attributes are spec'd

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/135.html" title="Last updated on May 16, 2025, 12:01 AM UTC (df24975)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/135/409d267...robbiemc:df24975.html" title="Last updated on May 16, 2025, 12:01 AM UTC (df24975)">Diff</a>
> spec: Define the request to ResourceType mapping

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/136.html" title="Last updated on May 16, 2025, 8:37 PM UTC (87238f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/136/409d267...ZelinLiu2022:87238f4.html" title="Last updated on May 16, 2025, 8:37 PM UTC (87238f4)">Diff</a>
> Spec: "newwindow" event rework

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/137.html" title="Last updated on May 22, 2025, 7:46 AM UTC (df538bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/137/66f2374...ZelinLiu2022:df538bb.html" title="Last updated on May 22, 2025, 7:46 AM UTC (df538bb)">Diff</a>
> spec: Fix red box in Context Menu spec

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/140.html" title="Last updated on Jun 13, 2025, 6:04 PM UTC (ea67d6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/140/bf638d4...robbiemc:ea67d6a.html" title="Last updated on Jun 13, 2025, 6:04 PM UTC (ea67d6a)">Diff</a>
> spec: Update canGoBack/Forward to return Promises

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/139.html" title="Last updated on Jun 16, 2025, 11:56 PM UTC (025aae1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/139/bf638d4...robbiemc:025aae1.html" title="Last updated on Jun 16, 2025, 11:56 PM UTC (025aae1)">Diff</a>
> spec: Update ContextMenus spec to reflect API changes

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/138.html" title="Last updated on Jun 20, 2025, 9:24 PM UTC (2fecf6c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/138/95935ba...robbiemc:2fecf6c.html" title="Last updated on Jun 20, 2025, 9:24 PM UTC (2fecf6c)">Diff</a>
> spec: Update WebRequest spec to reflect API changes

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/141.html" title="Last updated on Jun 20, 2025, 11:37 PM UTC (eae0591)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/141/bdea359...robbiemc:eae0591.html" title="Last updated on Jun 20, 2025, 11:37 PM UTC (eae0591)">Diff</a>
> spec: Spec URLPattern matching behavior

- index.bs
This addresses Dom's feedback from #138
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/144.html" title="Last updated on Jul 11, 2025, 6:56 PM UTC (4ace29e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/144/6b80fb0...robbiemc:4ace29e.html" title="Last updated on Jul 11, 2025, 6:56 PM UTC (4ace29e)">Diff</a>
> spec: Address WebRequest spec feedback
