WICG/controlled-frame

test_app/controlledframe_api.js

This commit fixes a couple of errors when using the captureVisibleRegion() controls in the test app.

JS error fixes for captureVisibleRegion()

---

.gitignore

This should make it less likely that we'll accidentally check in a copy of the spec that will grow stale over time.

Add index.html to .gitignore

---

README.md

Add a link to the WIP specification and source. Since the explainer exists in README.md, this makes the specification link available from https://github.com/chasephillips/controlled-frame/, too.

Explainer: Add link to specification

---

index.bs

This commit starts the IDL definition for the Controlled Frame API. It defines the attributes of <controlledframe> except for the `request` property. It also omits the ContextMenus.onShow property, since it differs from a standard Event, so it would require more thought into how it should be defined. It doesn't have an addEventListener() or other EventTarget interface methods; instead it defines its own addListener() method.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/controlled-frame/pull/20.html" title="Last updated on May 19, 2023, 9:33 PM UTC (d499f87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/chasephillips/controlled-frame/20/8305919...odejesush:d499f87.html" title="Last updated on May 19, 2023, 9:33 PM UTC (d499f87)">Diff</a>

spec: Start Controlled Frame IDL

---

test_app/controlledframe_api.js
test_app/index.html

This commit fixes the parsing for the contextMenus.create and contextMenus.update parameters. The fix is to prevent the fields in the parameter object from being set when the input fields don't have a value. The internal API implementation does not consider an empty string field to be the same as undefined, so this caused the API to not work properly in the test app.

test app: Fix contextMenus.create paramter parsing

---

test_app/README.md

This commit adds instructions for how the --user-data-dir flag can be used to start Chrome in a new profile separate from the main one.

Add user-data-dir flag details to test app README

---

test_app/manifest.webmanifest

This commit fixes the IWA installation on recent source code builds of Chrome due to the manifest missing the "version" field.

Fix IWA install by adding version to manifest

---

test_app/controlledframe_api.js
test_app/index.html

This commit fixes the readContentScriptDetails() method of ControlledFrameController. Values that are empty were being included in the ContentScriptDetails object, which was causing the API to produce an error.

testapp: Fix readContentScriptDetails()

---

test_app/manifest.webmanifest

This commit adds the cross-origin-isolated permission policy field to the manifest. Without this field, Controlled Frame no longer works.

Add the cross-origin-isolated policy

---

test_app/controlledframe_api.js

This commit fixes the context menus events for onShow and onClicked. Currently, the only way to add the event listener is to use contextMenus.on{Show,Clicked}.addListener(listener).

testapp: Fix Context Menus events

---

test_app/controlledframe_api.js

When the executeScript call is made, the receiving API for this call requires that only one of 'code' or 'file' is received. Sending both at the same time will trigger a failure. Update the caller to only send one of these keys in the object arguments at a time.

executeScript: Send 'code' or 'file' args exclusive of one another

---

test_app/README.md

Chrome now supports a dev mode proxy install process via chrome://web-app-internals. This commit updates the demo instructions to use the new process and stops using the command-line flags. We expect the command-line flags to be removed in an upcoming Chrome version.

test_app: Update demo instructions to use web-app-internals install

---

index.bs

This commit adds a non-normative block to describe what the navigation APIs do. The descriptions are taken from equivalent APIs available for history (go, back, forward), navigation (canGoBack, canGoForward) and window (reload, stop).
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/controlled-frame/pull/31.html" title="Last updated on Oct 31, 2023, 9:09 PM UTC (fe5cdeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/31/57a7e59...odejesush:fe5cdeb.html" title="Last updated on Oct 31, 2023, 9:09 PM UTC (fe5cdeb)">Diff</a>

Non-normative block for navigation APIs

---

test_app/controlledframe_api.js
test_app/index.html

insertCSS() should use a separate details section since it will require CSS by default which the test app can supply.
While here, add headings to break up the different content injection settings.

test_app: Fix insertCSS() to use a separate details section

---

test_app/index.html

addContentScripts() should use <all_urls> to match on. This will ensure that whatever URL the frame is displaying will match the provided JS from the test app.
insertCSS() assumes the provided value is CSS that can be applied to a given page. This commit fixes the CSS syntax used and adds !important which will override any existing CSS rules for the body's background color.

test_app: Fix addContentScripts and insertCSS

---

index.bs

This commit adds the IDL definition for the scripting methods of Controlled Frame. This includes:
* addContentScripts
* executeScript
* insertCSS
* removeContentScript
* and their related types
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/controlled-frame/pull/38.html" title="Last updated on Jan 31, 2024, 10:44 PM UTC (4ef2ee9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/38/64bb258...odejesush:4ef2ee9.html" title="Last updated on Jan 31, 2024, 10:44 PM UTC (4ef2ee9)">Diff</a>

spec: Define scripting methods IDL

---

index.bs

This commit defines the IDL for Controlled Frame's configuration related APIs. These include
* clearData
* getAudioState
* getZoom
* isAudioMuted
* setAudioMuted
* setZoom
* and related types
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/controlled-frame/pull/39.html" title="Last updated on Jan 31, 2024, 11:20 PM UTC (8f41ba3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/39/64bb258...odejesush:8f41ba3.html" title="Last updated on Jan 31, 2024, 11:20 PM UTC (8f41ba3)">Diff</a>

spec: Define configuration methods IDL

---

test_app/README.md

Part of recent work separated Controlled Frame from the IWA feature flag. Now, Controlled Frame has to be enabled separately from IWAs.

test_app: Add ControlledFrame feature flag to launch command line

---

test_app/README.md

Make a series of changes to the demo instructions:
* Remove references to old version numbers
* Simplify and streamline the chrome install instructions on Linux
* Remove the linux build instructions section
* Improve headings
* Improve copy to help with readability

test_app: Update demo instructions

---

.github/workflows/build-spec.yml
.github/workflows/build-test-app.yml
test_app/bump_version.js
test_app/package.json

This attempts to create a workflow that will automatically run whenever a commit changes anything in test_app. It will bump the version number (in the test-app-vX tag), build the app, generate an update manifest, and publish a new release with the new swbn file and an update manifest with all known versions.
This is based on the auto-deploy setup in https://github.com/chromeos/iwa-sink, with some additional complexity to deal with the fact that test_app isn't the only thing in this repo.

test_app: Set up autorelease

---

index.bs

This defines the IDL of the Controlled Frame WebRequest API, but does not include any normative or non-normative text further specifying it.
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/58.html" title="Last updated on Jan 28, 2025, 11:43 PM UTC (816aa03)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/58/c10e650...robbiemc:816aa03.html" title="Last updated on Jan 28, 2025, 11:43 PM UTC (816aa03)">Diff</a>

spec: Define WebRequest IDL

---

index.bs

- Fix URL attribute to point to controlled-frame spec site
- Update HTMLControlledFrame to be HTMLControlledFrameElement
- Update casing on maxheight et al to match "maxHeight"
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/pull/61.html" title="Last updated on Feb 3, 2025, 8:57 PM UTC (e178554)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/61/ed6b6f2...e178554.html" title="Last updated on Feb 3, 2025, 8:57 PM UTC (e178554)">Diff</a>

spec: Address quick feedback from issue 60

---

index.bs

As part of fixes to the implementation, we made these promise-based. Update the spec to reflect that change.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/pull/63.html" title="Last updated on Feb 4, 2025, 1:06 AM UTC (b7140a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/63/4ea8de3...b7140a6.html" title="Last updated on Feb 4, 2025, 1:06 AM UTC (b7140a6)">Diff</a>

spec: Update addContentScripts and removeContentScripts to be async

---

index.bs
test_app/src/web_request_test.js

This defines most of the event listener infrastructure for the WebRequest spec. It doesn't monkeypatch in any changes to fetch yet, or define documentId, requestId, frameId.
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/62.html" title="Last updated on Feb 13, 2025, 11:51 PM UTC (d8012d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/62/4ea8de3...robbiemc:d8012d3.html" title="Last updated on Feb 13, 2025, 11:51 PM UTC (d8012d3)">Diff</a>

spec: Define WebRequest spec

---

index.bs

This adds a disclaimer about WebRequest and ContextMenus not currently following Web API norms.
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/72.html" title="Last updated on Feb 27, 2025, 8:09 AM UTC (3fb09cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/72/356da9c...robbiemc:3fb09cb.html" title="Last updated on Feb 27, 2025, 8:09 AM UTC (3fb09cb)">Diff</a>

spec: Add disclaimer about WR and CM

---

test_app/index.html
test_app/src/controlledframe_api.js

This converts all not-yet-promisified APIs in the test_app to promises. It also removes an unused tabId parameter and makes the canGoBack/Forward checkboxes readonly as they're not meant to be controlled by the user.

test_app: Promisify remaining methods

---

index.bs

Addressing feedback from Dominic to adjust the IDL naming schemes to more closely match expectations with web standards.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/pull/80.html" title="Last updated on Mar 4, 2025, 7:47 PM UTC (867af73)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/80/a61ea26...867af73.html" title="Last updated on Mar 4, 2025, 7:47 PM UTC (867af73)">Diff</a>

spec: Update IDL entries for RunAt enum and ContentScriptDetails

---

index.bs

This adds a "Categories" section to the element definition.
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/83.html" title="Last updated on Mar 5, 2025, 12:28 AM UTC (5dcd915)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/83/a61ea26...robbiemc:5dcd915.html" title="Last updated on Mar 5, 2025, 12:28 AM UTC (5dcd915)">Diff</a>

spec: Add element categories

---

index.bs

This makes a few changes, mostly based on feedback from #78:
- Noted that the "persist:" partition prefix should be opaque to embedded content.
- Removed TODO about waiting for navigation completion. As far as I can tell the navigation algorithm we're calling already waits for completion.
- Replaced remaining uses of "validate embedded content" with embedderParent null checks.
- This touched most of the configuration/capture methods to somewhat improve them, but more work is needed on them.
- Added double keying to the network partition key.
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/90.html" title="Last updated on Mar 25, 2025, 12:02 AM UTC (20a3178)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/90/7bab23e...robbiemc …

spec: Miscellaneous cleanup

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/98.html" title="Last updated on Apr 23, 2025, 1:24 AM UTC (b89fe74)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/98/166517c...robbiemc:b89fe74.html" title="Last updated on Apr 23, 2025, 1:24 AM UTC (b89fe74)">Diff</a>

spec: Fix spec vs dictionary member access syntax in WebRequest spec

---

index.bs

This updates all WebRequest handlers to execute their JS handlers in the correct task source, and addresses other miscellaneous feedback from Reilly.
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/100.html" title="Last updated on Apr 29, 2025, 4:55 PM UTC (9738aeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/100/ed00011...robbiemc:9738aeb.html" title="Last updated on Apr 29, 2025, 4:55 PM UTC (9738aeb)">Diff</a>

spec: Update WebRequest handlers to execute in the correct task source

---

test_app/src/controlledframe_api.js

This updates the test app to await return return value of canGoBack/Forward in preparation of them returning a promise. This is safe before that change goes in because calling await on a non-promise just returns the value (`await true === true`).

test_app: Await canGoBack/Forward return value

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/115.html" title="Last updated on May 8, 2025, 9:00 PM UTC (b095c69)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/115/ae483d9...ZelinLiu2022:b095c69.html" title="Last updated on May 8, 2025, 9:00 PM UTC (b095c69)">Diff</a>

spec: Remove Promise.all and remove optional in definition parameters

---

index.bs

This addresses a TODO in the zoom and capture sections.
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/116.html" title="Last updated on May 9, 2025, 9:31 PM UTC (54686e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/116/a5f8de2...robbiemc:54686e7.html" title="Last updated on May 9, 2025, 9:31 PM UTC (54686e7)">Diff</a>

spec: Resolve some TODOs

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/119.html" title="Last updated on May 13, 2025, 2:04 AM UTC (47ab39f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/119/6f19a98...ZelinLiu2022:47ab39f.html" title="Last updated on May 13, 2025, 2:04 AM UTC (47ab39f)">Diff</a>

spec: Use 'parse a URL' instead of 'URL parser'

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/ZelinLiu2022/controlled-frame/pull/123.html" title="Last updated on May 14, 2025, 6:06 PM UTC (b58d400)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/123/d61b659...ZelinLiu2022:b58d400.html" title="Last updated on May 14, 2025, 6:06 PM UTC (b58d400)">Diff</a>

spec: Fire LoadRedirectEvent now takes URL instead of USVString

---

index.bs

This adds links to the iframe a11y rules, which are the same as what we want.
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/133.html" title="Last updated on May 15, 2025, 8:00 PM UTC (d0177c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/133/48e2e71...robbiemc:d0177c7.html" title="Last updated on May 15, 2025, 8:00 PM UTC (d0177c7)">Diff</a>

spec: Add a11y considerations

---

index.bs

This addresses the last of Dom's feedback from #144.
***
<a href="https://pr-preview.s3.amazonaws.com/robbiemc/controlled-frame/pull/145.html" title="Last updated on Jul 14, 2025, 9:18 PM UTC (f997db3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/controlled-frame/145/5d810bd...robbiemc:f997db3.html" title="Last updated on Jul 14, 2025, 9:18 PM UTC (f997db3)">Diff</a>

spec: Rename embedderParent to controlledFrameEmbedderParent
